---
- name: HedgeDoc | Create Consul service definition
  include_role: name=infra-role-consul-service
  vars:
    consul_config_name: '{{ hedgedoc_service_name }}'
    consul_services:
      - name: '{{ hedgedoc_service_name }}'
        tags: ['hedgedoc', 'notes', 'misc']
        # we advertise the port with basic auth
        port: '{{ hedgedoc_app_cont_port }}'
        checks:
          - id: '{{ hedgedoc_service_name }}-status'
            name: 'HedgeDoc Healthcheck'
            type: 'http'
            http: 'http://localhost:{{ hedgedoc_app_cont_port }}/config'
